### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by patrickkusebauch** [rchouinard/newrelic-nginx-plugin#1]
It would be immensely helpful to have some screenshots of the plugin in NewRelic. Right now I have no idea what information the plugin actually collects nor how it is displayed in NewRelic. I believe that a simple screenshot could go a long way in deciding which NGINX plugin to chose.

**Comment by rchouinard** [comment]
The plugin collects/displays the following data:

Overview
- Connections
- Request rate

Connections
- Active
- Idle
- Accept rate
- Drop rate

Requests
- Active
- Rate

I'll get some captures and update the README this evening. Of course, I'm also always open to suggestions on the dashboard, so if it doesn't quite do what you want let me know; I want this plugin to be as helpful as possible.
